"""add_status_to_audit_log

Revision ID: d803c2e6cd9d
Revises: 84a1d5271cf2
Create Date: 2026-02-25 19:10:47.775645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd803c2e6cd9d'
down_revision: Union[str, Sequence[str], None] = '84a1d5271cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'status')
    # ### end Alembic commands ###
